services:
    planossauro-frontend:
        restart: always
        build: .
        ports:
            - 8081:8080
        networks:
            - frontend_network
networks:
    frontend_network:
        driver: bridge
