services:
    planossauro-frontend:
        restart: always
        build: .
        ports:
            - 8080:8080
        networks:
            - frontend_network
        deploy:
            resources:
                limits:
                    memory: 128M
networks:
    frontend_network:
        driver: bridge
